export const teamMembers = [
  {
    id: 1,
    name: "Aria Chen",
    role: "Gateway Support",
    department: "Technical",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=b6e3f4",
    bio: "5+ years helping clients navigate complex payment gateway integrations. Expert in API troubleshooting and real-time transaction monitoring.",
    stats: { tickets: "2.4k", rating: "4.9", response: "< 2min" },
    color: "#e8f4fd",
  },
  {
    id: 2,
    name: "Olivia Martinez",
    role: "Payments Support",
    department: "Finance",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=olivia&backgroundColor=ffd5dc",
    bio: "Specialist in international payment flows and currency conversion issues. Fluent in 3 languages to serve our global customer base.",
    stats: { tickets: "3.1k", rating: "4.8", response: "< 3min" },
    color: "#fdf0f3",
  },
  {
    id: 3,
    name: "Richard Mills",
    role: "Payments Support",
    department: "Finance",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=richard&backgroundColor=c0aede",
    bio: "Focused on subscription billing, failed payment recovery, and chargeback management. Passionate about reducing revenue leakage.",
    stats: { tickets: "1.9k", rating: "4.9", response: "< 4min" },
    color: "#f3f0fd",
  },
  {
    id: 4,
    name: "Viola Bassett",
    role: "Customer Success Lead",
    department: "Success",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=viola&backgroundColor=d1f4e0",
    bio: "Leads a team of 12 success specialists. Architected our onboarding program that reduced churn by 34% in 2023. Obsessed with customer outcomes.",
    stats: { tickets: "4.5k", rating: "5.0", response: "< 1min" },
    color: "#f0fdf4",
  },
  {
    id: 5,
    name: "Sophie Chamberlain",
    role: "Specialized Support",
    department: "Enterprise",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sophie&backgroundColor=fde68a",
    bio: "Dedicated to high-touch enterprise accounts. Background in fintech consulting. Handles complex compliance and regulatory questions.",
    stats: { tickets: "890", rating: "4.9", response: "< 5min" },
    color: "#fffbeb",
  },
  {
    id: 6,
    name: "Erik Anders",
    role: "VP of Customer Success",
    department: "Leadership",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=erik&backgroundColor=a5f3fc",
    bio: "10-year veteran in customer success leadership. Scaled support operations from 2 to 60+ specialists. Believes great support is a growth engine.",
    stats: { tickets: "7.2k", rating: "4.9", response: "< 2min" },
    color: "#ecfeff",
  },
  {
    id: 7,
    name: "Natalie Carter",
    role: "Customer Success Agent",
    department: "Success",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=natalie&backgroundColor=fed7aa",
    bio: "Rising star on the success team with a knack for turning frustrated users into loyal advocates. Specializes in onboarding new merchants.",
    stats: { tickets: "1.2k", rating: "4.8", response: "< 3min" },
    color: "#fff7ed",
  },
  {
    id: 8,
    name: "Marcus Webb",
    role: "Technical Support",
    department: "Technical",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus&backgroundColor=bbf7d0",
    bio: "Full-stack developer turned support specialist. Bridges the gap between engineering and customers, translating complex issues into plain English.",
    stats: { tickets: "2.8k", rating: "4.7", response: "< 6min" },
    color: "#f0fdf4",
  },
];